CREATE TABLE MOVIE (
  ID            SERIAL PRIMARY KEY,
  NAME          TEXT NOT NULL,
  RELEASE_YEAR  INT NOT NULL,
  DESCRIPTION   TEXT,
  DURATION      INT NOT NULL,
  RATING        VARCHAR(5),
  CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
